#
# Makefile by MakeMaker
# 21/06/2017 12:31 CEST
# Folders wrapper
#

# Ensure we can compute the rest of the Makefile
ifndef	MKMK_HOME
$(error Error the variable 'MKMK_HOME' is not defined!)
endif

# Target is Folders, current sub-sub-dir
LANG=Folders
TYPE=.

# Include the skeleton defined for the language
include ${MKMK_HOME}/Makefiles/rules/Folders/rule-Folders.mk

# Ensure Makefile wrapper is always up todate
include ${MKMK_HOME}/Makefiles/rules/rule-Makefile-update.mk
