#
# Makefile by MakeMaker
# 21/06/2017 12:31 CEST
# C++ Executable wrapper
#

# Ensure we can compute the rest of the Makefile
ifndef	MKMK_HOME
$(error Error the variable 'MKMK_HOME' is not defined!)
endif

# Target is C++, Executable.
LANG=C++
TYPE=EXE

# Include the skeleton defined for the language
include ${MKMK_HOME}/Makefiles/skeleton/skel-${LANG}-${TYPE}.mk

# Ensure Makefile wrapper is always up todate
include ${MKMK_HOME}/Makefiles/rules/rule-Makefile-update.mk
